#!/bin/bash

if [[ $# -ne 0 ]]; then
    echo "Do not pass any parameters to this script!"
    exit 1
fi

echo "Building all containers in 'build/'"
for BUILDNAME in $(ls builds)
do
    ./build $BUILDNAME
done
