#!/bin/bash

function print_buildnames {
    echo "Valid buildnames are:"
    for FILE in $(ls builds)
    do
        echo $FILE
    done
}

if [[ $# -ne 1 ]]; then
    echo "Usage: '$0 buildname'"
    print_buildnames
    exit 1
fi

if [[ ! -d "builds/$1" ]]; then
    echo "'$1' is not a valid buildname"
    print_buildnames
    exit 2
fi

echo "Building container '$1'"
docker build -f "builds/"$1"/Dockerfile" -t i"cpe23dc_"$1 .
